import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartStoreProvider } from "@/lib/store/cart-store-provider";
import { ThemeToggle } from "@/components/light-dark-mode/ThemeToggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartStoreProvider>
          <header className="p-4 flex justify-end">
            <ThemeToggle />
          </header>
          {children}
        </CartStoreProvider>
      </body>
    </html>
  );
}
